### ISSUE TITLE
Server provisioner (devel) is failing

### ISSUE THREAD

**Issue by termlen0** [ansible/workshops#1011]
##### SUMMARY

The provisioner is failing at the "install product demos task". Skipping this task allows provisioning to work. I would recommend that we also include an option to not install demos for this task, using the "demo" extra-var.

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below
---
# region where the nodes will live
ec2_region: us-west-1
# name prefix for all the VMs
ec2_name_prefix: server-automation
# amount of work benches to provision
student_total: 1
# workshop is put into rhel mode
workshop_type: rhel
workshop_dns_zone: rhtelco.io
## Optional Variables
# password used for student account on control node
admin_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
# this will install Ansible Tower on all control nodes
towerinstall: true
create_cluster: yes
autolicense: true
create_login_page: false
code_server: false
# IBM Community Grid - defaults to true if you don't tell the provisioner
ibm_community_grid: false
demo: no

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### FAILING TASK
```

- name: install product_demos collection
  shell: "{{item}}"
  loop:
    - "ansible-galaxy collection install ansible.product_demos --force-with-deps"
    - "ansible-galaxy collection install awx.awx --force-with-deps"
  register: galaxy
  until: galaxy is not failed
  retries: 5
  when:
    - towerinstall
```

##### PLAYBOOK SHORT OUTPUT

```paste below
failed: [localhost] (item=ansible-galaxy collection install awx.awx --force-with-deps) => changed=true 
  ansible_loop_var: item
  attempts: 5
  cmd: ansible-galaxy collection install awx.awx --force-with-deps
  delta: '0:00:01.661415'
  end: '2020-10-31 17:21:27.479307'
  item: ansible-galaxy collection install awx.awx --force-with-deps
  msg: non-zero return code
  rc: 250
  start: '2020-10-31 17:21:25.817892'
  stderr: 'ERROR! Unexpected Exception, this is probably a bug: ''str'' object has no attribute ''get'''
  stderr_lines: <omitted>
  stdout: |-
    Process install dependency map
    |to see the full traceback, use -vvv
  stdout_lines: <omitted>
```

##### PLAYBOOK LONG OUTPUT

```paste below

```
