### ISSUE TITLE
Pull Subscription Manifest dynamically via RH API

### ISSUE THREAD

**Issue by kenmoini** [ansible/workshops#1104]
##### SUMMARY
Currently the Ansible provisioners look for a `tower_license.json` or `manifest.zip` file to provide Tower a subscription - it's sometimes difficult to pull in those assets.  A more fluid method would be to dynamically pull in a Subscription Manifest via the Red Hat APIs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
Providing a subscription manifest on the file system is more challenging compared to providing a RH API Offline Token and using the RH APIs to download the manifest dynamically, especially in Tower-driven environments.  How about a working example to demonstrate?

rh-api-vars.yml
```yaml
generation_directory: /tmp/wherever/you/wanna/put/it
rhsm_api_token: yourLongOfflineRHAPIToken
rhsm_tower_allocation_uuid: STRINGS-HERE-FOR-YOUR-SUB-ALLOCATION-UUID
```

rh-api-tasks.yml
```yaml
- name: Log into RH SSO API
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    body_format: form-urlencoded
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rhsm_api_token }}"
  register: rh_sso_reg
  tags:
    - tower_license

- name: Trigger Manifest Export
  uri:
    url: "https://api.access.redhat.com/management/v1/allocations/{{ rhsm_tower_allocation_uuid }}/export"
    status_code: 200
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  register: trigger_manifest_export_reg
  tags:
    - tower_license

- name: Check status of Manifest ExportJob
  uri:
    url: "{{ trigger_manifest_export_reg.json.body.href }}"
    status_code: 200
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  register: check_manifest_export_reg
  until: check_manifest_export_reg.status == 200
  retries: 10
  delay: 10
  ignore_errors: true
  tags:
    - tower_license

- name: Download Manifest
  get_url:
    url: "{{ check_manifest_export_reg.json.body.href }}"
    dest: "{{ generation_directory }}/tower_sub_manifest.zip"
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  tags:
    - tower_license
```
