### ISSUE TITLE
Docs around needed Ansible Collections and Pip Modules

### ISSUE THREAD

**Issue by kenmoini** [ansible/workshops#1105]
##### SUMMARY
Deploying the Ansible Workshops requires a number of prerequisites that aren't documented such as Ansible Collections and pip modules.

##### ISSUE TYPE
 - Bug Report

##### EXTRA VARS FILE
```yaml
---
# Where to provision (Don't change: only testing ec2)
instance_loc: ec2
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: aw1n
# creates student_total of workbenches for the workshop
student_total: 2
# Set the right workshop type, like networking, rhel or f5 (see above)
workshop_type: windows
# OPTIONAL VARIABLES
# creates 2 windows instances per student instead of default 1
doubleup: false
# password for Ansible control node, defaults to ansible
admin_password: ansible123
# adds a form that prompts for name and email to allocate student credentials
attendance: true
# automatically installs Tower to control node
towerinstall: true
create_cluster: false
workshop_dns_zone: sandbox1721.opentlc.com
```

##### ANSIBLE VERSION
```
ansible 2.10.1
  config file = /home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/kemo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kemo/.local/lib/python3.6/site-packages/ansible
  executable location = /home/kemo/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = ['time']
DEFAULT_FORKS(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = ['/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Windows Subsystem for Linux, Ubuntu Distro

##### TOWER
Not tested in Tower yet, which would be worse considering there is no `collections/requirements.yml` file...

##### PLAYBOOK SHORT OUTPUT

```paste below
TASK [include_role : workshop_attendance] ****************************************************************
ERROR! couldn't resolve module/action 'mysql_db'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/kemo/Development/tmpAnsibleWorkshops/workshops/provisioner/roles/workshop_attendance/tasks/attendance.yml': line 60, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create a new database with name 'workshop'
  ^ here

AND OTHERS - already fixed two issues in collection requirements and pip modules.
```

##### PLAYBOOK LONG OUTPUT
```paste below
No need, and my scroll back is short, it's just modules and collections that need to be automated/documented
```

##### PROPOSED FIX

`collections/requirements.yml`
```yaml
---
collections:
  - name: ansible.windows
  - name: community.mysql
```

Adding to One-Time Setup:

```
#### Ansible Collections

The provisioning Playbooks and Roles require a series of Ansible Collections - install them on your Ansible Control node with the following command:

`ansible-galaxy install -r collections/requirements.yml`
```

And amend the pip module instructions in the one-time setup to the following:

```
pip install boto boto3 netaddr passlib pywinrm requests requests-credssp
```
