### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by kenmoini** [ansible/workshops#1106]
##### SUMMARY
It'd be great to have tags that correspond to the role names that way you could skip a few stages in the provisioning process.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
See the `provision_lab.yml` Playbook?  Would be great to skip over some steps to speed up debugging and development.
Something like this would work well:

```yaml
---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tags:
    - preflight_checks
  tasks:
    - name: run pre-check role to make sure workshop will complete provisioning
      include_role:
        name: workshop_check_setup
      tags:
        - workshop_check_setup

    - name: run AWS check setup if using AWS
      include_role:
        name: aws_check_setup
      tags:
        - aws_check_setup

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - manage_ec2_instances
  pre_tasks:
    - name: Cluster nodes
      set_fact:
        control_nodes: 4
      when: create_cluster is defined and create_cluster|bool
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes:attendance"
  become: true
  gather_facts: false
  tags:
    - connectivity_test
  roles:
    - connectivity_test

- name: Configure nginx on attendance host
  hosts: attendance
  become: true
  gather_facts: true
  tasks:
    - block:
        - include_role:
            name: workshop_attendance_nginx
          tags:
            - workshop_attendance_nginx
        - include_role:
            name: workshop_attendance
          tags:
            - workshop_attendance
      when: attendance|bool
```

And so on...thoughts?
