### ISSUE TITLE
Error building automation-controller Instruqt image. Missing var `ec2_name_prefix`

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1284]
#### Summary 
Error message when building the automation-controller image. Missing `ec2_name_prefix` variable. 

#### Error
```bash
packer build --force automation-controller.pkr.hcl
```
```bash
googlecompute.automation-controller:     "msg": "The task includes an option with an undefined variable. The error was: {{ playbook_dir }}/{{ ec2_name_prefix }}: 'ec2_name_prefix' is undefined\n\nThe error appears to be in '/home/craig/.ansible/collections/ansible_collections/ansible/workshops/roles/control_node/tasks/20_all_workshop.yml'
```
#### Cause
https://github.com/ansible/workshops/blob/91ee454bdcbee33d551a96431b15de3ce4e37569/roles/control_node/tasks/20_all_workshop.yml#L62

```yaml
- name: Put ssh-key in proper spot for student
  copy:
    src: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    dest: "/home/{{ username }}/.ssh/id_rsa"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0400
```

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

```bash
packer build --force automation-controller.pkr.hcl
```
```bash
googlecompute.automation-controller:     "msg": "The task includes an option with an undefined variable. The error was: {{ playbook_dir }}/{{ ec2_name_prefix }}: 'ec2_name_prefix' is undefined\n\nThe error appears to be in '/home/craig/.ansible/collections/ansible_collections/ansible/workshops/roles/control_node/tasks/20_all_workshop.yml'

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 24
