### ISSUE TITLE
Remove command-line Linux users from control node

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#1665]
### Problem Summary

The only purpose that I can think of for the student users is to ascertain which workbench you are on.  I think we can simplify provisioning significantly by copying what we do on Instruqt and have just the user `rhel`

This would let me pre-build a lot of these tasks: `roles/control_node/tasks/20_all_workshop.yml`

and one of them is a significant time suck and ripe for failure
```
# Pull specific EE for each workshop based on workshop name
- name: Pull execution environment for {{ workshop_type }} workshop
  become_user: "{{ username }}"
  containers.podman.podman_image:
    name: "{{ lookup('vars', workshop_type + '_ee') }}"
  register: podman_pull
  until: podman_pull is not failed
  retries: 5
  when: workshop_type is defined
```

We will still use students on the attendance page... just not on the command line... every student's experience will match 

### Issue Type

Feature Request

### Extra vars file

n/a

### Ansible Playbook Output

n/a

### Ansible Version

n/a

### Ansible Configuration

n/a

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

n/a
