### ISSUE TITLE
F5 Lab not deploying correctly due to incorrect playbook_dir

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#1683]
### Problem Summary

During testing i was able to figure out there is a code bug located at roles/f5_setup/tasks/main.yml

This code calls for  {{ playbook_dir }} this variable changes when it is called from /git/workshops-aap2/provisioner/workshop_specific

1) /workshop/provisioner/provision.yml calls /workshop/provisioner/workshop_specific/f5.yml
2) /workshop/provisioner/workshop_specific/f5.yml calls /workshop/roles/f5_setup/tasks/main.yml  (This is when playbook DIR Changes to /workshop/provisioner/workshop_specific/f5.yml
3) code below fails because {{playbook_dir}} is /workshop/provisioner/workshop_specific/ not /workshop/provisioner/ where the pem file is located.

```
- name: Change BIG-IP F5 mgmt password
  f5networks.f5_modules.bigip_command:
    provider:
      ssh_keyfile: "{{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
      transport: cli
      user: admin
      server: "{{ ansible_host }}"
    commands: "modify auth user admin password {{ admin_password }}"
  register: change_password
  until: change_password is not failed
  retries: 5
  delay: 10

```

My current workaround for this is to change the code from above to the below (with the [:-18] to remove last 18 chars)

`      ssh_keyfile: "{{playbook_dir[:-18]}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"`

### Issue Type

Bug

### Extra vars file

```
---
# region where the nodes will live
ec2_region: us-west-2
# name prefix for all the VMs
ec2_name_prefix: MMABIS-AnsibleGH
# amount of work benches to provision
student_total: 50
# workshp runs in F5 mode
workshop_type: f5
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token: "OMITED"
# Required for podman authentication to registry.redhat.io
redhat_username: OMITED
redhat_password: "OMITED"
# DNS domain
workshop_dns_zone: "f5demo.net"
## Optional Variables
# password used for student account on control node
admin_password: Ansible123!
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
create_cluster: false
ibm_community_grid: false
```

### Ansible Playbook Output

Dont have it on hand the error is 

"File doesnt exist  /workshop/provisioner/**workshop_specific**/MMABIS-AnsibleGH/MMABIS-AnsibleGH-private.pem"

### Ansible Version

[root@DS9 workshops-aap2]# ansible --version
ansible [core 2.12.4]
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible
python version = 3.9.6 (default, Nov 9 2021, 13:31:27) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
jinja version = 3.1.1
libyaml = True

### Ansible Configuration

[root@DS9 workshops-aap2]# ansible-config dump --only-changed
[root@DS9 workshops-aap2]#

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Happend on RHEL (Latest) and Rocky Linux (Python 3.9)
