### ISSUE TITLE
Chocolately playbook fixes

### ISSUE THREAD

**Issue by vap0rtranz** [ansible/workshops#1735]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

The Chocolately playbook example won't run because it is missing several variables.  See https://aap2.demoredhat.com/exercises/ansible_windows/8-chocolatey/

These snippets of the install_packages.yml fix the documentation gaps:

```
  - name: install version of packages in order
    chocolatey.chocolatey.win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    loop: "{{ choco_packages }}"
```
...

```
  - ansible.builtin.debug:
      msg: "python version is {{ check_python_version }} and NodeJS version is {{ check_node_version }}"
```
