### ISSUE TITLE
Provisioner enforces prebuilt images (unavailable and unknown to public) as defaults

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#1945]
### Problem Summary

When using the Provisioner, and existing documentation there is no reference to the `pre_build: false` parameter that is needed in the extravars file.  

this causes 2 main issues 

1. its undocumented that it needs to be disabled for Non-RedHat users as these prebuilt images are accessible to RH only personel or people shared to these images.
2. no documentation exists on how to disable the use of pre-built images and do the standard installation for outside users.  
(The example given on the workshop site doesnt contain this information ) https://github.com/ansible/workshops/blob/devel/provisioner/README.md

I would have marked this as a docbug but i also do not feel like Enabled for prebuilt images should be the default of this provisioner as it makes it very closed off natively to anyone who would like to use the lab outside of RH. 

### Issue Type

Bug

### Extra vars file
```
---
# region where the nodes will live
ec2_region: us-west-2

# name prefix for all the VMs
ec2_name_prefix: f5-testdrive-test 
#F5-TestDrive-Test

# creates student_total of workbenches for the workshop
student_total: 1 

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: f5

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "..."

# Required for podman authentication to registry.redhat.io
redhat_username: MyRHUser
redhat_password: "s^perSecretP@ss!"

#####OPTIONAL VARIABLES

# add prebuilt false
pre_build: false

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: s^perSecretP@ss!

# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: "mydomain.com"

# automatically installs Tower to control node
controllerinstall: true

# SHA value of targeted AAP bundle setup files.
provided_sha_value: 7456b98f2f50e0e1d4c93fb4e375fe8a9174f397a5b1c0950915224f7f020ec4

# default vars for ec2 AMIs (ec2_info) are located in provisioner/roles/manage_ec2_instances/defaults/main/main.yml
# select ec2_info AMI vars can be overwritten via ec2_xtra vars, e.g.:
ec2_xtra:
  f5node:
    owners: 679593333241
    size: t2.large
    os_type: linux
    disk_volume_type: gp3
    disk_space: 82
    disk_iops: 3000
    disk_throughput: 125
    architecture: x86_64
    filter: 'F5 BIGIP-16*PAYG-Best 25Mbps*'
    username: admin

f5_ee: "quay.io/f5_business_development/mmabis-ee-test:latest"
```
### Ansible Playbook Output

Error will present that i do not have access to pre-built images specified in roles/manage_ec2_instances/defaults/main/main.yml

```
pre_build_controller_ami:
  ap-northeast-1: ami-03d31ba6351d7b468
  ap-southeast-1: ami-08684e30290b9409e
  eu-central-1: ami-01e8bf4dc63f8a847
  us-east-1: ami-0a27c9386391d6f48
```

### Ansible Version
```
[ec2-user@ip-10-0-100-29 provisioner]$ ansible --version
ansible [core 2.14.4]
  config file = /git/workshops-main-branch/provisioner/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.9.16 (main, Dec  8 2022, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
### Ansible Configuration
```
[ec2-user@ip-10-0-100-29 provisioner]$ ansible-config dump --only-changed
CONFIG_FILE() = /git/workshops-main-branch/provisioner/ansible.cfg
DEFAULT_FORKS(/git/workshops-main-branch/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/git/workshops-main-branch/provisioner/ansible.cfg) = ['/git/workshops-main-branch/provisioner/hosts']
HOST_KEY_CHECKING(/git/workshops-main-branch/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/git/workshops-main-branch/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/git/workshops-main-branch/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/git/workshops-main-branch/provisioner/ansible.cfg) = False
```
### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System
```
[ec2-user@ip-10-0-100-29 provisioner]$ cat /etc/redhat-release 
CentOS Stream release 9
```
