### ISSUE TITLE
Update F5 Lab Student Inventory File for updated code

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#1947]
### Problem Summary

Would like the code updated in student inventory to reflect updated code and python interpreter as there have been issues with the incorrect interpreter being called from execution engines as well as populate the port used in the F5 for the management console. 

file to be updated would be located in roles/manage_ec2_instances/templates/student_inventory/instances_f5.j2

code changes requested are  Lines (6 [ansible_python_interpreter=/usr/bin/python3
] and Line 12 [server_port=8443]) 

```
[all:vars]
ansible_user=student{{ item }}
ansible_password={{ admin_password }}
{% if ssh_port is defined %}
ansible_port={{ ssh_port }}
ansible_python_interpreter=/usr/bin/python3
{% endif %}

[lb]
{% for vm in f5_node_facts.instances %}
{% if 'student' + item == vm.tags.Student %}
f5 ansible_host={{ vm.public_ip_address }} ansible_user=admin private_ip={{ vm.private_ip_address }} ansible_password={{admin_password}} server_port=8443
{% endif %}
{% endfor %}

[control]
{% for vm in ansible_node_facts.instances %}
{% if 'student' + item == vm.tags.Student %}
ansible ansible_host={{ vm.public_ip_address }} ansible_user={{ vm.tags.username }} private_ip={{ vm.private_ip_address }}
{% endif %}
{% endfor %}

[web]
{% for vm in f5_node1_node_facts.instances %}
{% if 'student' + item == vm.tags.Student %}
node1 ansible_host={{ vm.public_ip_address }} ansible_user={{ vm.tags.username }} private_ip={{ vm.private_ip_address }}
{% endif %}
{% endfor %}
{% for vm in f5_node2_node_facts.instances %}
{% if 'student' + item == vm.tags.Student %}
node2 ansible_host={{ vm.public_ip_address }} ansible_user={{ vm.tags.username }} private_ip={{ vm.private_ip_address }}
{% endif %}
{% endfor %}

```

### Issue Type

Bug

### Extra vars file

```
---
# region where the nodes will live
ec2_region: us-west-2

# name prefix for all the VMs
ec2_name_prefix: f5-testdrive-test 
#F5-TestDrive-Test

# creates student_total of workbenches for the workshop
student_total: 1 

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: f5

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "..."

# Required for podman authentication to registry.redhat.io
redhat_username: MyRHUser
redhat_password: "s^perSecretP@ss!"

#####OPTIONAL VARIABLES

# add prebuilt false
pre_build: false

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: s^perSecretP@ss!

# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: "mydomain.com"

# automatically installs Tower to control node
controllerinstall: true

# SHA value of targeted AAP bundle setup files.
provided_sha_value: 7456b98f2f50e0e1d4c93fb4e375fe8a9174f397a5b1c0950915224f7f020ec4

# default vars for ec2 AMIs (ec2_info) are located in provisioner/roles/manage_ec2_instances/defaults/main/main.yml
# select ec2_info AMI vars can be overwritten via ec2_xtra vars, e.g.:
ec2_xtra:
  f5node:
    owners: 679593333241
    size: t3.large
    os_type: linux
    disk_volume_type: gp3
    disk_space: 100
    disk_iops: 3000
    disk_throughput: 125
    architecture: x86_64
    filter: 'F5 BIGIP-16.*PAYG-Best 25Mbps*'
    username: admin

f5_ee: "quay.io/f5_business_development/mmabis-ee-test:latest"
```

### Ansible Playbook Output

No Fails occur, except during the lab code when the python interpreter called within the EE fails on certain versions of our code

### Ansible Version

```
[ec2-user@ip-10-0-100-29 provisioner]$ ansible --version
ansible [core 2.14.4]
  config file = /git/workshops-main-branch/provisioner/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.9.16 (main, Dec  8 2022, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Ansible Configuration

```
[ec2-user@ip-10-0-100-29 provisioner]$ ansible-config dump --only-changed
CONFIG_FILE() = /git/workshops-main-branch/provisioner/ansible.cfg
DEFAULT_FORKS(/git/workshops-main-branch/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/git/workshops-main-branch/provisioner/ansible.cfg) = ['/git/workshops-main-branch/provisioner/hosts']
HOST_KEY_CHECKING(/git/workshops-main-branch/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/git/workshops-main-branch/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/git/workshops-main-branch/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/git/workshops-main-branch/provisioner/ansible.cfg) = False
```

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

```
[ec2-user@ip-10-0-100-29 provisioner]$ cat /etc/redhat-release 
CentOS Stream release 9
```
