### ISSUE TITLE
[TYPO] Step 7 - Using Facts in Playbooks 

### ISSUE THREAD

**Issue by sillihkram** [ansible/workshops#1986]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes
```

---
- name: Output facts within a playbook
  hosts: all
  tasks:
  - name: Prints Ansible facts
    ansible.builtin.debug:
      msg: The default IPv4 address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}
```
