### ISSUE TITLE
[Typo] 1.5-handlers ftpserver.yml

### ISSUE THREAD

**Issue by sillihkram** [ansible/workshops#1987]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

```
---
- name: Install vsftpd on ftpservers
  hosts: all
  become: true
  tasks:
    - name: Install FTP server when host in ftpserver group
      ansible.builtin.yum:
        name: vsftpd
        state: latest
      when: inventory_hostname in groups["ftpserver"]
```
