### ISSUE TITLE
Windows workshop - reboot required when IIS gets installed

### ISSUE THREAD

**Issue by sebw** [ansible/workshops#2139]
### Problem Summary

Most students get the following error in chapter 4 step 6

```
TASK [Start iis service] *******************************************************
fatal: [student1-win1]: FAILED! => {"changed": false, "exists": false, "msg": "Service 'W3Svc' is not installed, need to set 'path' to create a new service"}
```

Install of features might require a reboot. We should invite student to add this in `install_iis.yml`

```
- name: Install IIS Web-Server with sub features and management tools
  ansible.windows.win_feature:
    name: Web-Server
    state: present
  register: win_feature

- name: Reboot if installing Web-Server feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required
```

### Issue Type

Documentation

### Extra vars file

None

### Ansible Playbook Output

See above

### Ansible Version

AAP

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

N/A
