### ISSUE TITLE
Ansible Automation Platform 2 Networking Automation Workshop failing to provision

### ISSUE THREAD

**Issue by andrew-jones** [ansible/workshops#2248]
### Problem Summary

We are seeing errors attempting to provision of the workshop 'Ansible Automation Platform 2 Networking Automation Workshop' workshop.

Error at this task;

```
TASK [../roles/manage_ec2_instances : save ami for juniper (NETWORKING MODE)]

The task includes an option with an undefined variable. The error was: No last item, sequence was empty.. No last item, sequence was empty.
The error appears to be in '/runner/project/roles/manage_ec2_instances/tasks/ami_find/ami_find_network.yml': line 50, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: save ami for juniper (NETWORKING MODE)
      ^ here
```

### Issue Type

Bug

### Extra vars file

```
automation_hub: true
aws_region: us-east-2
cloud_provider: ec2
guid: wnddh
network_type: juniper
num_users: 1
platform: rhpds
uuid: 90879e72-c151-595f-bd04-e67b079f58db
__meta__:
  anarchy:
    namespace: babylon-anarchy-aap2-workshop
  ansible_control_plane:
    type: controller
  ansible_controller_select_mode: first-available
  ansible_controllers:
    - hostname: aap2-prod-us-east-2.aap.infra.demo.redhat.com
    - hostname: aap2-prod-us-west-2.aap.infra.demo.redhat.com
  asset_uuid: dbeee484-12e4-44da-964a-d997154f6f66
  aws_sandboxed: false
  catalog:
    category: Workshops
    description:
      content: >
        <p>Discover how to automate popular network data center devices using
        Ansible playbooks.</p>

        <p>This catalog items is a comprehensive beginners guide to automating
        popular network data center devices from Arista, Cisco, and Juniper
        using Ansible playbooks. You learn how to pull facts from devices, build
        templated network configurations, and apply these concepts at scale with
        the automation controller in Red Hat Ansible Automation Platform. You
        put it all together by exploring the controller’s job templates,
        surveys, access controls, and more.

        <p>


        <h4>Specifications</h4>

        <ul>
          <li>One automation controller on Red Hat Enterprise Linux 8</li>
          <li>Two Arista EOS</li>
          <li>One Cisco IOS</li>
          <li>One Juniper Junos</li>
        </ul>

        <h4>Supporting Materials</h4>

        <p><b>Access guide:</b> After you complete provisioning, you receive an
        email with a website containing a user credential and access to the
        following:

        </p>
          <ul>
          <li>Automation controller web UI</li>
          <li>Visual Studio Code (including a terminal)</li>
          <li>Backup direct SSH access</li>
        </ul>

        <p>The website provided with this information is dynamically created
        upon provisioning. The web address is your four-digit unique
        identification number plus the GPTE DNS "open.redhat.com"--for example:
        http://87f8.open.redhat.com/

        </p>

        <p><b>Lab materials:</b> All lab materials can be found <a
        href="https://aap2.demoredhat.com/">here</a>:</p>

        <ul>
          <li><a href="https://aap2.demoredhat.com/exercises/ansible_network/">Network exercises</a></li>
          <li>Slide deck
            <ul>
            <li>Public: <a href="https://aap2.demoredhat.com/decks/ansible_network.pdf">PDF</a></li>
            <li>Red Hat-only: <a href="https://docs.google.com/presentation/d/1PIT-kGAGMVEEK8PsuZCoyzFC5CIzLBwdnftnUsdUNWQ/edit?usp=sharing">Google source</a></li>
            </ul>

          <li><a href=">https://github.com/ansible/workshops">GitHub</a>
        </ul>
            <p><b>Support resources:</b></p>
        <ul>

        <li> Red Hat employees can join the Slack Chat <a
        href="https://redhat.enterprise.slack.com/archives/CCCHEV2UA">Ansible
        Workshops & Demos</a> chat room.</li>

        <li>View the <a
        href="https://source.redhat.com/departments/marketing/globalcampaignsteamgtc/automation/automation_wiki/ansible_workshops">Ansible
        Technical Workshops Kits</a> source page.</li>

        <li>For issues with workshop content, material, and so on, please open
        an issue on <a
        href=”https://github.com/ansible/workshops/issues/new/choose”>GitHub</a>.</li>

        <li>Red Hat partners can join us on <a
        href=”https://join.slack.com/t/ansiblenetwork/shared_invite/zt-3zeqmhhx-zuID9uJqbbpZ2KdVeTwvzw”>external
        Slack.</a></li>

        <li>For issues with Red Hat Product Demo System (RHPDS), urgent upcoming
        workshops, and so on, please open an issue <a
        href="https://red.ht/RHPDS-Request">here</a>.
          </ul>
        <p><b>Provisioning time:</b> Typically, ~45 minutes</p>
      format: html
    display_name: Ansible Automation Platform 2 Networking Automation Workshop
    icon:
      alt: Red Hat Ansible Automation Platform
      url: >-
        https://gpte-public.s3.amazonaws.com/babylon-catalog/catalog-icon-aap.svg
    keywords:
      - aap2
      - ansible
      - arista
      - cisco
      - juniper
      - networking
      - automation
    labels:
      Product: Red_Hat_Ansible_Automation_Platform
      Product_Family: Red_Hat_Automation
      Provider: Ansible_BU
    namespace: babylon-catalog-{{ stage | default('?') }}
    parameters:
      - annotation: pfe.redhat.com/salesforce-id
        description: Salesforce Number, Campaign ID, CDH, or Project ID.
        formLabel: Salesforce ID
        formRequireCondition: >-
          typeof purpose === 'string' && purpose.startsWith("Customer Activity -
          ")
        name: salesforce_id
        openAPIV3Schema:
          type: string
        validation: >-
          check_salesforce_id(salesforce_id) || Error('Valid Salesforce ID
          required for all Customer Facing Events')
      - annotation: demo.redhat.com/purpose
        description: Purpose for the service.
        formLabel: Purpose
        name: purpose
        openAPIV3Schema:
          type: string
          x-form-options:
            - activity: Customer Facing
              description: Showing a product/solution to a customer or prospect
              name: Show a demo to a customer
              sfdcRequired: true
            - activity: Customer Facing
              description: >-
                Performing a hands on activity with an individual customer or
                prospect
              name: Conduct a hands on workshop for one customer
              sfdcRequired: true
            - activity: Customer Facing
              description: >-
                Using an environment to build and show a customer or prospect
                the capabilities of Red Hat solutions
              name: Build a proof of concept for a customer
              requireUserInput: true
              sfdcRequired: true
            - activity: Customer Facing
              description: >-
                Performing a demo or workshop for a Marketing event for multiple
                customers (tied to a campaign ID)
              name: Conduct a Marketing event with multiple customers
              sfdcRequired: true
            - activity: Customer Facing
              description: >-
                Only select this option if the current purpose fields do not
                meet your needs. You will be prompted to add a description of
                your purpose in a text field so that we may better understand
                your reason for utilizing our platform
              name: Other
              requireUserInput: true
              sfdcRequired: true
            - activity: Partner Facing
              description: Showing a product/solution to a Partner
              name: Conduct a demo to a Partner
              sfdcRequired: false
            - activity: Partner Facing
              description: Performing a hands on activity with Partners
              name: Conduct an enablement workshop to Partners
              sfdcRequired: false
            - activity: Partner Facing
              description: >-
                Using an environment to build and show a customer or prospect
                the capabilities of Red Hat solutions with a Partner
              name: Assist a Partner with a proof of concept
              sfdcRequired: false
            - activity: Partner Facing
              description: >-
                Assist a Partner in performing a demo or workshop for multiple
                customers who share common business challenges
              name: Assist a Partner with running an event for multiple customers
              sfdcRequired: true
            - activity: Partner Facing
              description: >-
                Only select this option if the current purpose fields do not
                meet your needs. You will be prompted to add a description of
                your purpose in a text field so that we may better understand
                your reason for utilizing our platform
              name: Other
              requireUserInput: true
              sfdcRequired: true
            - activity: Practice / Enablement
              description: >-
                Setting up and practicing with an environment to be able to
                perform a customer demo
              name: Practice for a demo
              sfdcRequired: true
            - activity: Practice / Enablement
              description: >-
                Setting up and practicing with an environment to be able to
                conduct a customer workshop
              name: Practice for a workshop
              sfdcRequired: true
            - activity: Practice / Enablement
              description: >-
                Exploring Red Hat products in an active terminal to better
                understand their business value
              name: Learning about the product
              sfdcRequired: false
            - activity: Practice / Enablement
              description: >-
                Setting up an environment to test a potential product solution
                for a business challenge
              name: Trying out a technical solution
              sfdcRequired: false
            - activity: Practice / Enablement
              description: >-
                For consultants to set up and practice with an environment for a
                service solution
              name: Preparing for a customer service engagement
              sfdcRequired: false
            - activity: Practice / Enablement
              description: >-
                Using an environment to train team members/perform an internal
                Red Hat training
              name: Conduct internal training/enablement
              sfdcRequired: false
            - activity: Practice / Enablement
              description: >-
                Only select this option if the current purpose fields do not
                meet your needs. You will be prompted to add a description of
                your purpose in a text field so that we may better understand
                your reason for utilizing our platform
              name: Other
              requireUserInput: true
              sfdcRequired: true
            - activity: Brand Event
              description: ''
              name: AnsibleFest 2025
              requiredRoles:
                - rhpds-devs-rh1
                - rhpds-admins
                - rhpds-devs-summit
              sfdcRequired: false
            - activity: Brand Event
              description: ''
              name: Summit 2025
              requiredRoles:
                - rhpds-devs-rh1
                - rhpds-admins
                - rhpds-devs-summit
              sfdcRequired: false
            - activity: Brand Event
              description: ''
              name: Innovation Day
              requiredRoles:
                - rhpds-devs-rh1
                - rhpds-admins
                - rhpds-devs-summit
              sfdcRequired: false
            - activity: Brand Event
              description: ''
              name: Summit Connect 2025
              requiredRoles:
                - rhpds-devs-rh1
                - rhpds-admins
                - rhpds-devs-summit
              sfdcRequired: false
            - activity: Brand Event
              description: ''
              name: Other
              requireUserInput: true
              requiredRoles:
                - rhpds-devs-rh1
                - rhpds-admins
              sfdcRequired: false
            - activity: Asset Development
              description: >-
                For use when existing Red Hat Demo Platform assets do not meet
                your customer’s needs and you need to develop a custom demo to
                show a product’s business value; use when you anticipate the
                demo becoming an Enterprise Standard asset for the Demo Platform
                team to maintain and support (this means developing your code
                with AgnosticD/V)
              name: Developing a custom demo
              requiredRoles:
                - rhpds-devs
                - rhpds-admins
                - babylon-admins
              sfdcRequired: false
            - activity: Asset Development
              description: >-
                For use when existing Red Hat Demo Platform assets do not meet
                your customer’s needs and you do not wish to develop your custom
                demo using AgnosticD/V; by developing a community demo, you
                agree to maintain the code in your own git repo. The Demo
                Platform team will maintain the base asset used to develop your
                community demo
              name: Developing a community demo
              requiredRoles:
                - rhpds-devs
                - rhpds-admins
              sfdcRequired: false
            - activity: Asset Development
              description: >-
                Only select this option if the current purpose fields do not
                meet your needs. You will be prompted to add a description of
                your purpose in a text field so that we may better understand
                your reason for utilizing our platform
              name: Other
              requireUserInput: true
              requiredRoles:
                - rhpds-devs
                - rhpds-admins
              sfdcRequired: false
            - activity: Admin
              description: ''
              name: Asset Development
              requiredRoles:
                - rhpds-admins
              sfdcRequired: false
            - activity: Admin
              description: ''
              name: Asset Maintenance
              requiredRoles:
                - rhpds-admins
              sfdcRequired: false
            - activity: Admin
              description: ''
              name: QA
              requiredRoles:
                - rhpds-admins
              sfdcRequired: false
            - activity: Admin
              description: >-
                Only select this option if the current purpose fields do not
                meet your needs. You will be prompted to add a description of
                your purpose in a text field so that we may better understand
                your reason for utilizing our platform
              name: Other
              requireUserInput: true
              requiredRoles:
                - rhpds-admins
              sfdcRequired: false
        required: true
      - description: Enable Automation Hub
        formGroup: Features
        formLabel: Enable Automation Hub
        name: automation_hub
        openAPIV3Schema:
          default: false
          type: boolean
      - description: AWS Region to Provision Environment.
        formLabel: Region
        name: aws_region
        openAPIV3Schema:
          default: us-east-2
          enum:
            - us-east-2
            - ap-southeast-1
            - eu-central-1
          type: string
        required: true
      - description: Number of users to provision within the environment.
        formLabel: User Count
        name: num_users
        openAPIV3Schema:
          default: 1
          maximum: 110
          minimum: 1
          type: integer
      - description: Select Network Type (Select none for Multivendor)
        formLabel: Network Type (Select none for Multivendor)
        name: network_type
        openAPIV3Schema:
          default: multivendor
          enum:
            - cisco
            - juniper
            - arista
            - multivendor
          type: string
        required: false
    reportingLabels:
      primaryBU: Automation
    terms_of_service: >-
      <p>

      Please pay close attention to the information provided on this
      page.<br/><br/>

      You understand that the usage costs associated with this order will be
      charged back to your cost center.<br/>

      You affirm that you are reporting truthful information in accordance with
      the Red Hat code of ethics.<br/>

      The ordered environment will cease to run unless you extend the Auto-Stop
      in Services.<br/>

      The ordered environment will cease to exist at the Auto-Destroy date and
      time.<br/>

      If you have read and understood the above, click the check box below then
      Submit to continue.

      </p>
    workshopUiDisabled: true
  deployer:
    actions:
      destroy:
        entry_point: provisioner/teardown_lab.yml
      provision:
        entry_point: provisioner/provision_lab.yml
      start:
        disable: true
      status:
        disable: true
      stop:
        disable: true
      update:
        disable: true
    credentials:
      - rhpds-aws-prod
    execution_environment:
      name: aap2-workshop-networking
    scm_ref: rhpds-workshops-aap2-prod
    scm_type: git
    scm_url: https://github.com/redhat-gpe/workshops.git
    type: ansible-workshops
  last_update:
    git:
      author: Billy Bethell <93923166+bbethell-1@users.noreply.github.com>
      committer: GitHub <noreply@github.com>
      hash: 60e8da4610013ec47e856e61f90a2ab638e002b4
      message: Update purpose.yaml (#19826)
      when_author: '2025-03-19T13:23:41Z'
      when_committer: '2025-03-19T13:23:41Z'
  lifespan:
    default: 30h
    maximum: 180d
    relativeMaximum: 30d
  runtime:
    default: 9999h
    maximum: 9999h
  scheduler:
    data:
      annotations:
        env_type: '{{ env_type }}'
        guid: '{{ guid }}'
        purpose: '{{ purpose | default('''') }}'
      uuid: '{{ uuid }}'
    enable: false
  secrets:
    - name: agnostics-api-mgr-access
      var: agnostics_mgr_access
    - name: gpte-db
      namespace: gpte
      var: gpte_db
    - name: gpte-vault-0
      namespace: gpte
      var: vault_credentials
    - name: aap2-workshop
      namespace: gpte
  tower:
    organization: RHPDS
admin_password: >-
  {{ lookup("ansible.builtin.password", "/tmp/" ~ guid ~ "-admin_password
  chars=ascii_lowercase,digits length=8") }}
ansible_workshops_version: devel
aws_cli_destroy_ec2: true
cloud_tags:
  env_type: '{{ env_type }}'
  platform: '{{ platform | default(''unknown'') }}'
controller_configuration_projects_async_delay: 5
controller_configuration_projects_async_retries: 36
controller_install_command: ./setup.sh -e gpgcheck=0
controllerinstall: true
dns_type: aws
ec2_name_prefix: '{{ guid }}'
ec2_region: '{{ aws_region }}'
ec2_xtra:
  juniper:
    ami: '{{ juniper_ami | default(omit) }}'
    filter: junos-vsrx3-x86-64-22.3R2*byol*
    os: junos
    size: c5.xlarge
    username: ec2-user
    volume:
      - device_name: /dev/sda1
        ebs:
          delete_on_termination: true
          iops: 1000
          volume_size: 40
          volume_type: io1
env_type: aap2-workshop-networking-automation
install_ftl: false
ocp4_installer_root_url: https://mirror.openshift.com/pub/openshift-v4/clients
output_dir: /runner/project/provisioner/{{ guid }}
pre_build: true
provided_sha_value: 161b45950284c0798cfa8fd6b0d6a0d80a29d1d0ca2063b83da1569f477190f7
purpose: production
rhpds_info_output: true
ssh_authorized_keys:
  - key: >-
      ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABAQCvZvn+GL0wTOsAdh1ikIQoqj2Fw/RA6F14O347rgKdpkgOQpGQk1k2gM8wcla2Y1o0bPIzwlNy1oh5o9uNjZDMeDcEXWuXbu0cRBy4pVRhh8a8zAZfssnqoXHHLyPyHWpdTmgIhr0UIGYrzHrnySAnUcDp3gJuE46UEBtrlyv94cVvZf+EZUTaZ+2KjTRLoNryCn7vKoGHQBooYg1DeHLcLSRWEADUo+bP0y64+X/XTMZOAXbf8kTXocqAgfl/usbYdfLOgwU6zWuj8vxzAKuMEXS1AJSp5aeqRKlbbw40IkTmLoQIgJdb2Zt98BH/xHDe9xxhscUCfWeS37XLp75J
      opentlc_admin_backdoor
  - key: >-
      ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQCg5PJgwAB8U2NiXh4aRZAg09f3xjT3y1CP322StmT4ljiqhXoqOOZ++qDIKFmtHGmeEjvkCo11M2oVmJTeaibeS0E+Xsoi9wTcit47h2ka7WPdzhy/togFQOVAftbwi3RtHDOweIFL18FQ8inhu9W/oFibsZjQEWtHoHtLkmA5zOSQtWDmVfx3iWrKd4svkNbJ+SNZMnD0tCDoot3y0Knzyt+wpZtVd94YXpUDTCJ8Ie1nFSdm7H/QB9/bDXeOSSnHBq2xSmywodNoyA1gFZ1hhpPNEauQjzeKCMpNLPATg/jtQb1zojG6QnO/7I5euKOlDeJ1Odg35aTG31p8EbT3UL8NZssdn3YY3OEQ/2rN0PaQ+zxzmzfh1otx4Rsh1IbD5S99GuQD2ma7m0zOzrBb8Mil5TCaTaK8mIADq/lclj0sAMrH1EXyFvDiHEG+cV0iMyXOxEMTJs4YLr8DyqsTZ34TvVSJP9/0YwQuRYhg0MJmFbMvl/4yibTgyvTYLN0=
      instructor-key-2022
  - key: >-
      ssh-ed25519
      AAAAC3NzaC1lZDI1NTE5AAAAIIIDDIOD4M5yYo3uCFDBDb6del+NG2fkboWh90kW/S6H
      elliptical_instructor_key_2024
  - key: >-
      ssh-ed25519
      AAAAC3NzaC1lZDI1NTE5AAAAIOBfsRMLCEQt86EZnvQ/rK49wo1odLqpd1NEz3tDjUWY
      elliptical_admin_key_2023
  - key: >-
      ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAACAQC3nKRSIwWn7pjMf2i1TyXgjsauEIoDS8Xulad2ZAbsmZrWcKU5hPi23xq0g2AjRYiXml8zSX9jAQfmlKnrXGYo5WN39iXGRI3lFJmXwmEHne3Z0qtUgt9MBA4w0Tcunw7pXniKntvo2oiDYZlXHztRMHMeUkUjLgCGjn2cfi0uqd4pxLmneMziHMKDxcyy+9MaGnWr5Bs27r3b6rWNFqG2fAo1Z5ZWEA/r3MhdI9ZzMRJVTUhunpstwMX8MRxx/OGk0zynyHcSkh91sqZ3xhPpvRkmYLRa5I0aw88AMenWBfc586FyORL2e/UVoIoyMkBMnovaRIoiTj74RuPeZ6gGKbbfpt1ggDs4j9Z1Go51GlGPYcchvLQvx+Ucv5+tLZSqZBhPOXLRqFuQgRZz4R6j5O5UkfdjLJxBoHQZxT0Wdzd/XiGcAlyDOq8puNSxdF3w/8eGGSKDdUONv1tc1dcTFd6kR+jYaedjD1fldVrC+4fRUFkFqEovDPVI4159VSqJWz78WuqazNnCRMVDnS4Le+Er1pvTbk5rOdYUkF67vxVwD3cyJ3D1C49wVsIc3+kngZN2246OEMsbVugEPG4A8/UOlHIE5iBps+mM9GX6UFSj4aLFh15XeOGKs7aH2r1thfvFPSvk12t8QvNDhhhhAf5EzzypvNEbXQ6fk3YSUw==
      rsa_admin_key_2023
student_total: '{{ num_users | int }}'
workshop_dns_zone: example.opentlc.com
workshop_type: network
aap_download_password: 43594e79-6151-4cc0-a310-8309145d55b4
aap_download_url: https://d244lrsdik4t7t.cloudfront.net/aap.tar.gz
aap_download_user: rhpds-private
manifest_download_password: 43594e79-6151-4cc0-a310-8309145d55b4
manifest_download_url: https://d244lrsdik4t7t.cloudfront.net/long-lived-controller-manifest.zip
manifest_download_user: rhpds-private
offline_token: >-
  eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2MjY4MDQ1ODYsImp0aSI6ImI3MjIyMmEwLTVkNTEtNDc0NS05NTk0LTFiZjhmNTcxZjE5NCIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpzZWFuY0ByZWRoYXQuY29tIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6InJoc20tYXBpIiwic2Vzc2lvbl9zdGF0ZSI6IjBiM2U2ZjA3LTVhOGQtNGM3MS1iMjEyLTA3NTUzNWQzOTM4YiIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MifQ.60y_ezoosYst_FJlZfVsud9qGbDt7QRly6nhprqVERE
redhat_password: 4Ue9tf$5PIJmpUCq&NY
redhat_username: ansible-labs
ACTION: provision
agnosticd_callback_url: >-
  https://anarchy-babylon-anarchy-aap2-workshop.apps.ocp-us-east-1.infra.open.redhat.com/action/ansiblebu.aap2-workshop-networking-automation.prod-wnddh-pmd76x
agnosticd_callback_token: 0jg004k7i28vt8repyf5la9ngah5y8st
```

### Ansible Playbook Output

https://aap2-prod-us-east-2.aap.infra.demo.redhat.com/#/jobs/playbook/1218180/output

```
TASK [../roles/manage_ec2_instances : save ami for juniper (NETWORKING MODE)]

The task includes an option with an undefined variable. The error was: No last item, sequence was empty.. No last item, sequence was empty.
The error appears to be in '/runner/project/roles/manage_ec2_instances/tasks/ami_find/ami_find_network.yml': line 50, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: save ami for juniper (NETWORKING MODE)
      ^ here
```

### Ansible Version

This is from the demo platform deployer, I believe this is the ee and version of ansible being run.

```
~ podman run -it --rm     quay.io/acme_corp/workshop_ee:bb2de800f0aa36bd76141ea9f81ee10bf32007e5 ansible --version
ansible [core 2.15.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.19 (main, Aug 26 2024, 11:01:47) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.9)
  jinja version = 3.1.4
  libyaml = True
```

### Ansible Configuration

```
➜  ~ podman run -it --rm     quay.io/acme_corp/workshop_ee:bb2de800f0aa36bd76141ea9f81ee10bf32007e5 ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
➜  ~ podman run -it --rm     quay.io/acme_corp/workshop_ee:bb2de800f0aa36bd76141ea9f81ee10bf32007e5 cat /etc/ansible/ansible.cfg      
# Since Ansible 2.12 (core):
# To generate an example config file (a "disabled" one with all default settings, commented out):
#               $ ansible-config init --disabled > ansible.cfg
#
# Also you can now have a more complete file by including existing plugins:
# ansible-config init --disabled -t all > ansible.cfg

# For previous versions of Ansible you can check for examples in the 'stable' branches of each version
# Note that this file was always incomplete  and lagging changes to configuration settings

# for example, for 2.9: https://github.com/ansible/ansible/blob/stable-2.9/examples/ansible.cfg
```

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL @ https://aap2-prod-us-east-2.aap.infra.demo.redhat.com
