### ISSUE TITLE
fix control node for f5 and networking to enable more generic role/scaffolding

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#743]
##### SUMMARY
need to fix exercise instructions so that networking and f5 can use more generic role/scaffolding

e.g. here is task we will have temporarily 

```
- name: Move relevant exercises to correct location  
  copy:
    src: "/tmp/workshops/exercises/ansible_{{workshop_type}}/"
    dest: "/home/{{ username }}/{{workshop_type}}-workshop"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
  when: 
    - workshop_type != f5
    - workshop_type != networking 
```

need to make sure conditionals are not needed all over the place, its like duct tape

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner
- exercises

##### ADDITIONAL INFORMATION
this is a placeholder....

will help with issue https://github.com/ansible/workshops/issues/683
