### ISSUE TITLE
"The ipaddr filter requires python's netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by MAdeelMalik** [ansible/workshops#752]
Dear All,
I am working on ansible tool and facing the following issue
FAILED! => {"changed": false, "msg": 

**"The ipaddr filter requires python's netaddr be installed on the ansible controller"**

}
May I know how can I resolve it?

I have already installed library  "netaddr" and "ipaddr"

[root@12-sv-np ~]# ansible --version
**ansible 2.9.5**
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  **python version = 3.6.8** (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

[root@12-sv-np ~]#  uname -a
**Linux 12-sv-np 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by MAdeelMalik** [comment]
After changing the OS from CentOS 8 to Ubuntu 18.0.4 then i can not face this issue in Ubuntu,
However, i did everything in cent os 8 but did not get success

**root@sv-np:~#  ansible --version**
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

**root@sv-np:~# uname -a**
Linux sv-np 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shamsalmon** [comment]
You need to ipaddress module installed as well. The error is kind of poor.

**Comment by MAdeelMalik** [comment]
I have already installed ipaddr and netaddr via pip. But still receiving this error

**Comment by IPvSean** [comment]
hey @MAdeelMalik this is the module that tests it->

```
    - name: make sure packages required are installed on this control node
      pip:
        name:
          - netaddr
      check_mode: true
      when: workshop_type == "networking"
      register: package_state
```

the play has this->
```
  connection: local
  become: false
```

You could reproduce this with a one task playbook like this->
```
---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: make sure packages required are installed on this control node
      pip:
        name:
          - netaddr
      check_mode: true
      when: workshop_type == "networking"
      register: package_state
```

try that, I imagine you will get identical results.  This means as the user you are running the Ansible Playbook it checks to make sure you have the pip package netaddr installed.  I have a guess that you are doing `sudo pip install netaddr` which would install it for the root user versus the current user (e.g. madeelmalik)

can you confirm or deny my suspicion?
