### ISSUE TITLE
RHEL Ex. 1.7 Incorrect HTML content destination

### ISSUE THREAD

**Issue by nleiva** [ansible/workshops#823]
##### SUMMARY

Destination for `tasks/main.yml` should point to an `index.html` file. It currently reas as:

```yaml
- name: deliver html content
  copy:
    src: web.html
    dest: "/var/www/vhosts/{{ ansible_hostname }}"
```

Correct line should be `dest: /var/www/vhosts/{{ ansible_hostname }}/index.html`.

##### ISSUE TYPE
- Documentation Report
