### ISSUE TITLE
manage_ec2_instance: F5 Workshop Image upgrade for TMUI Bug CVE-2020-5902

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#940]
SUMMARY
F5 Image needs to be pulled to protect for CVE-2020-5920 as per F5 KB: https://support.f5.com/csp/article/K52145254?utm_source=f5sirt&utm_medium=int_email

What will change?

- The Image will go from a Good 25MBPS Image to a Best 25MBPS Image which will allow for additional modules such as APM/ASM/AFM to be deployed.
- The Image will now deploy the latest 13.1.3.4 Image that is protected for the CVE-2020-5920 Bug where as the old image used was 13.1.0.4 

FILE NAME
roles/manage_ec2_instances/defaults/main/main.yml

OLD Code:
```  
f5node:
    owners: 679593333241
    size: t2.large
    os_type: linux
    disk_space: 40
    architecture: x86_64
    filter: 'F5 Networks Prelicensed Hourly BIGIP-13.1*Good 25MBPS*'
    username: admin
```

Updated Code with CVE Fixed BIG-IP:
```  
f5node:
    owners: 679593333241
    size: t2.large
    os_type: linux
    disk_space: 40
    architecture: x86_64
    filter: 'F5 BIGIP-13.1.*PAYG-Best 25Mbps*'
    username: admin
```
